version: "3.7"

services:
  content_database: 
    image: bitnami/postgresql
    container_name: DBContent
    ports: 
      - 5432:5432
    environment: 
      POSTGRESQL_PASSWORD: ${DB_PASSWORD_CONTENT_DATABASE}
      POSTGRESQL_DATABASE: ${DB_CONTENT_DATABASE}
    volumes: 
      - pg_content_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_CONTENT_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-net:
    driver: bridge

volumes:
  pg_content_data:
    driver: local